### ISSUE TITLE
Incorrect verbiage for domain_role check V-73221

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#11]
https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/8b5935dafb445e7f0d5eab6f898cee57ea6356fa/controls/V-73221.rb#L89-L95

The please update the verbiage to the effect of
```
This applies to member servers and standalone systems. A
  separate version applies to domain controllers.

```

**Comment by kkola** [comment]
3ad6f4d4c089c695f9361a96479f0fe32e0d3666 fixes this issue
