### ISSUE TITLE
Additional code needed for Domain controllers 'V-73283' 

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#12]
The control does not address, specific check for domain controllers.

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/e6e7ff348bc5e5ed205ae51595aaf703d9459af2/controls/V-73283.rb#L39

**Comment by kkola** [comment]
8c6279c4e99659e3d62e087fad9a04b18807b3a5 fixes this issue, but had to use a different set of commands to obtain the desired results
