### ISSUE TITLE
V-73393 adjust for inspec subject block limitation

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#17]
Inspec has a limitation where subject {} blocks does not function properly within a describe.one block

Same applies to an input() or attribute() block within a describe.one block

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73393.rb#L119-L130

Current design of the test results in powershell resource being unrecognized.
```
Message: undefined method `powershell' for #<RSpec::ExampleGroups::TheFilePermissionsOnADCNInfrastructureDCVsphereadDCNet:0x00007ff42e8cf0a8>
```

Please update the test to call the powershell call outside the describe.one block and place it in a variable.

The variable can be using within the subject{} block within the describe.one block

**Comment by kkola** [comment]
https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/commit/18cfb00590443680d4086fde6b36890642080f82 fixes this issue
