### ISSUE TITLE
V-73241	The Windows Server 2016 system must use an anti-virus program.	

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#3]
Tests should be updated to cover Windows Defender as well.

**Comment by karikarshivani** [comment]
A test was added to `V-73241` ([commit](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/pull/54/commits/18847d27ca6692a19a30664756ac8cf3c4a94dd2))
Here is the [json result](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6751588/V-73241.json.txt)

**Note:** Please rename the result files by removing the .txt extension to view the results in [Heimdall](https://heimdall-lite.mitre.org/)
