### ISSUE TITLE
V-73533 - Add clause for standalone systems

### ISSUE THREAD

**Issue by kclinden** [mitre/microsoft-windows-server-2016-stig-baseline#33]
This control is currently configured to check for DCs but not standalone systems. Need to add a check for if the system is on a domain or not.

This applies to member servers. For domain controllers and standalone systems, this is NA.

Something like this should work.

//Add line after 31
member_of_domain = command('(gwmi win32_computersystem).partofdomain').stdout.strip

//Add clause after 43
```
...
  if member_of_domain == 'False'
    impact 0.0
    desc 'This system is not a member of a domain, therefore this control is not applicable as it only applies to member servers'
  end
...
```

**Comment by karikarshivani** [comment]
Standardized the approach using [V-93419](https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/master/controls/V-93419.rb)
