### ISSUE TITLE
ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError) error

### ISSUE THREAD

**Issue by cchaffee** [mitre/microsoft-windows-server-2016-stig-baseline#4]
Running this on a Windows 2016 stock image and attempting to output the format in json yielded the UTF error.

This is related to https://github.com/inspec/inspec/issues/3375

I identified the following controls that cause the issue:

In controls `73607, 73609, 78127`, the `...` need's to be removed or escaped.

In control `73285` the `-` in `-AccountExpiring` needs to be escaped

```
controls/V-73285.rb:50:  Enter \"Search-ADAccount –AccountExpiring | FT Name, AccountExpirationDate\".
controls/V-73607.rb:73:  For each certificate with \"DoD Root CA…\" under \"Issued To\" and \"DoD
controls/V-73607.rb:74:  Interoperability Root CA…\" under \"Issued By\":
controls/V-73609.rb:66:  For each certificate with \"US DoD CCEB Interoperability Root CA …\" under
controls/V-78127.rb:28:(Unresolved SIDs have the format of \"*S-1-…\".)
```

After removing or escaping these, the output saves to json properly

**Comment by karikarshivani** [comment]
Updates were made to `V-73607`, `V-73609`, `V-78127` in the last two years and they are no longer causing an issue.
( [json result](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6751500/V-73607-73609-78127.json.txt) )

`V-73285` was updated ([commit hash: e80f5dc](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/pull/54/commits/e80f5dc29d8266c829bdf1ca16227f5256da0ae8)) with new logic and works fine now.
( [json result](https://github.com/mitre/microsoft-windows-server-2016-stig-baseline/files/6751540/V-73285.json.txt) )


**Note:** Please rename the result files by removing the .txt extension to view the results in [Heimdall](https://heimdall-lite.mitre.org/)
