### ISSUE TITLE
V-73307 Fails on Domain Controllers with PDC Emulator Role

### ISSUE THREAD

**Issue by slipthebit** [mitre/microsoft-windows-server-2016-stig-baseline#41]
Per the STIG, control V-73307 does not apply to domain controllers with the PDC Emulator role. V-73307.rb should skip if target is the PDC Emulator.

Per STIG, PDC Emulator can be determined using the command `Get-ADDomain | FT PDCEmulator`

**Comment by aaronlippold** [comment]
Hi,

Thanks for reporting, will you submit a PR to help us resolve this issue?

Thanks,
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by slipthebit** [comment]
I'll give it a try.

**Comment by slipthebit** [comment]
Closed initial PR to clean up branching. Opened PR #44 with corrected branching to isolate code change.

**Comment by karikarshivani** [comment]
Duplicate of #42 and addressed by PR #44
