### ISSUE TITLE
Incorrect NIST Tag

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#7]
Please remove the following lines from control V-73219 and V-73313.
It incorrectly overwrites a valid NIST tag specification above it.

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73219.rb#L22

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/0e48ee079b14b2799c22d28c2e40f986f3fdab4b/controls/V-73313.rb#L19

**Comment by kkola** [comment]
5fc4890ddb4788affa243fdd62814e55a29dc298 fixes this issue
