### ISSUE TITLE
Incorrect condition for Non applicable case

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-server-2016-stig-baseline#8]
Please update the following Non applicable case condition 

https://github.com/mitre/stig-microsoft-windows-server-2016-v1r4-baseline/blob/42fbf823bfe09d727a12476deda3762fe266e3f3/controls/V-73283.rb#L66

to 

```
if !temp_account.empty? 
```

**Comment by kkola** [comment]
e772321d4e60d55241fd5ff92e02ca0b7bc934d4 fixes this issue
